version: '3'
services:
  nodejs:
    image: node:alpine
    ports:
      - '3000:3000'
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    expose:
      - '3000'
    command: npm run dev